---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-app"
  namespace: "default"
  labels:
    app: "synedra-aim-app"
spec:
  ports:
  - protocol: "TCP"
    port: 8088
  selector:
    app: "synedra-aim-app"
  type: "ClusterIP"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synedra-data-node1-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synedra-aim-app-deployment
  labels:
    app: synedra-aim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synedra-aim-app
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: synedra-aim-app
    spec:
      containers:
        - name: synedra-aim-app
          image: gcr.io/synedra-innovations/aim-app-dockerhub:latest
          command: ["/root/startAIM.sh"]
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: "/data"
              subPath: "data"
              name: synedra-data-node1
      volumes:
        - name: synedra-data-node1
          persistentVolumeClaim:
            claimName: synedra-data-node1-disk
