
# Application
#
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-app"
  namespace: "default"
  labels:
    app: "synedra-aim-app"
spec:
  ports:
  - protocol: "TCP"
    port: 81
    name: control
  - protocol: "TCP"
    port: 80
    name: web-view
  - protocol: "TCP"
    port: 11210
    name: fsutilities
  - protocol: "TCP"
    port: 22
    name: "ssh"
  - protocol: "TCP"
    port: 11650
    name: "gateway-server"
  - protocol: "TCP"
    port: 8445
    name: "control-port-trusted"
  - protocol: "TCP"
    port: 11526
    name: "archiveserver-port-trusted"    
  - protocol: "TCP"
    port: 8446
    name: "control-port"
  selector:
    app: "synedra-aim-app"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-app-ext"
  namespace: "default"
  labels:
    app: "synedra-aim-app"
spec:
  ports:
  - protocol: "TCP"
    port: 443
    name: web-view-https
  - protocol: "TCP"
    port: 11650
    name: gateway-server
  selector:
    app: "synedra-aim-app"
  type: "LoadBalancer"
  loadBalancerIP: "34.76.45.196"
  #  loadBalancerIP: "34.102.183.146"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synedra-aim-node-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synedra-aim-app-deployment
  labels:
    app: synedra-aim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synedra-aim-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synedra-aim-app
    spec:
      containers:
        - name: synedra-aim-app
          image: gcr.io/synedra-innovations/aim-app:latest
#          command: ["/bin/sleep","86400"]
          command: ["/opt/synedra/scripts/startAIM.sh"]
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: "/data"
              subPath: "data"
              name: synedra-aim-node
      volumes:
        - name: synedra-aim-node
          persistentVolumeClaim:
            claimName: synedra-aim-node-disk
