apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-shiny-deployment
  labels:
    app: r-shiny-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r-shiny-deployment
  template:
    metadata:
      labels:
        app: r-shiny-deployment
    spec:
      containers:
      - name: r-shiny-deployment
        image: gcr.io/synedra-innovations/r-shiny3:latest
        command: ["/bin/sleep","86400"]
        command: ["/github/r-shiny3/start_container.sh"]
        ports:
        - containerPort: 3838
        - containerPort: 6533
---
apiVersion: v1
kind: Service
metadata:
  name: r-shiny-service
  labels:
    app: r-shiny
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3838
    name: shiny-server
    protocol: TCP
    targetPort: 3838
  - port: 6355
    name: shiny-commandline
    protocol: TCP
    targetPort: 6533
  selector:
    app: r-shiny-deployment
  sessionAffinity: None
  type: LoadBalancer
