#
# Database
#
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-db"
  namespace: "default"
  labels:
    app: "synedra-aim-db"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    name: "postgres"
  - protocol: "TCP"
    port: 22
    name: "ssh"
  selector:
    app: "synedra-aim-db"
  type: "ClusterIP"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synedra-aim-pg-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synedra-aim-db-deployment
  labels:
    app: synedra-aim-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synedra-aim-db
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: synedra-aim-db
    spec:
      containers:
        - name: synedra-aim-db
          image: gcr.io/synedra-innovations/aim-db:latest
          # command: ["/opt/synedra/scripts/start.sh"]
          ports:
            - containerPort: 5432
            - containerPort: 22
          volumeMounts:
            - mountPath: "/pg"
              subPath: "pg"
              name: synedra-aim-pg
          env:
            - name: PGDATA
              value: "/pg/data/data"
            - name: PGLOG
              value: "/pg/data/data/pgstartup.log"
            #- name: MYSQL_ALLOW_EMPTY_PASSWORD
            #value: "yes"
      volumes:
        - name: synedra-aim-pg
          persistentVolumeClaim:
            claimName: synedra-aim-pg-disk
---
#
# Application
#
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-app"
  namespace: "default"
  labels:
    app: "synedra-aim-app"
spec:
  ports:
  - protocol: "TCP"
    port: 81
    name: control
  - protocol: "TCP"
    port: 80
    name: web-view
  - protocol: "TCP"
    port: 11210
    name: fsutilities
  - protocol: "TCP"
    port: 22
    name: "ssh"    
  selector:
    app: "synedra-aim-app"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "synedra-aim-app-ext"
  namespace: "default"
  labels:
    app: "synedra-aim-app"
spec:
  ports:
  - protocol: "TCP"
    port: 443
    name: web-view-https
  - protocol: "TCP"
    port: 11650
    name: gateway-server
  selector:
    app: "synedra-aim-app"
  type: "LoadBalancer"
  #  loadBalancerIP: "34.102.183.146"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synedra-aim-node-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synedra-aim-app-deployment
  labels:
    app: synedra-aim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synedra-aim-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synedra-aim-app
    spec:
      containers:
        - name: synedra-aim-app
          image: gcr.io/synedra-innovations/aim-app:latest
#          command: ["/bin/sleep","86400"]
          command: ["/opt/synedra/scripts/startAIM.sh"]
          ports:
            - containerPort: 8088
          volumeMounts:
            - mountPath: "/data"
              subPath: "data"
              name: synedra-aim-node
      volumes:
        - name: synedra-aim-node
          persistentVolumeClaim:
            claimName: synedra-aim-node-disk
---
#
# Monitor
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-deployment
  labels:
    app: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace
          image: gcr.io/synedra-innovations/workspace:latest
