apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
#     volumes:
#     - name: secret-volume
#       secret:
#          secretName: nginx-certs-keys 
#     - name: configmap-volume
#       configMap:
#         name: nginxconfigmap 
      containers:
      - name: nginx-deployment
        image: gcr.io/synedra-innovations/nginx:latest
        command: ["/bin/sleep","86400"]
        ports:
        - containerPort: 443
        - containerPort: 80
#       livenessProbe:
#         httpGet:
#           path: /index.html
#           port: 80
#         initialDelaySeconds: 30
#         timeoutSeconds: 1
#       volumeMounts:
#       - mountPath: /etc/nginx/ssl
#         name: secret-volume
#       - mountPath: /etc/nginx/conf.d
#         name: configmap-volume 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: LoadBalancer
---
