# Flask Cluster
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-deployment
  template:
    metadata:
      labels:
        app: flask-deployment
    spec:
      containers:
        - name: flask-deployment
          image: gcr.io/synedra-innovations/cloud-docker-flask-example:latest
          command: ["/github/cloud-docker-flask-example/Script/start_container.sh"]
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-deployment
  name: flask-deployment-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-deployment
  sessionAffinity: None
  type: LoadBalancer
