---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-express-deployment-service"
  namespace: "default"
  labels:
    app: "mongo-express"
spec:
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  selector:
    app: "mongo-express"
  type: "LoadBalancer"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-deployment-service
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root-deployment-service
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
              value: example
