---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synedra-share-disk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

#
# Workspace
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-deployment
  labels:
    app: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace
          image: gcr.io/synedra-innovations/workspace:latest
          command: ["/opt/synedra/scripts/healthcheck-loop.sh"]
#         command: ["/bin/sleep", "86400"]
          volumeMounts:
            - mountPath: "/share"
              subPath: "share"
              name: synedra-share-disk
      volumes:
        - name: synedra-share-disk
          persistentVolumeClaim:
            claimName: synedra-share-disk
