#
# Workspace
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-deployment
  labels:
    app: workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workspace
    spec:
      containers:
        - name: workspace
          image: gcr.io/synedra-innovations/workspace:latest
          command: ["/opt/synedra/scripts/healthcheck-loop.sh"]
